<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.10" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Solly.UI\Solly.UI.csproj" />
      <ProjectReference Include="..\SollyUI.Demo.Shared\SollyUI.Demo.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Pages\Home.razor" />
      <_ContentIncludedByDefault Remove="Pages\NotFound.razor" />
      <_ContentIncludedByDefault Remove="Layout\MainLayout.razor" />
    </ItemGroup>

</Project>
